In [19]:
import pandas as pd
pd.set_option("display.max_columns", None)
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import pickle
sns.set_theme(style="whitegrid")

In [20]:
df = pd.read_pickle('data/yearly_df.pkl')
df.head(10)

,yearID,franchID,W,R,AB,H,2B,3B,HR,BB,SO,SB,SF,RA,ER,ERA,CG,SHO,SV,HA,HRA,BBA,SOA,E,DP,FP,BPF,PPF,DivWin_Y,WCWin_Y,LgWin_Y,WSWin_Y,run_diff,ba,linedrivepercent,xobp,xwoba,vegas_win_total
0,2017,STL,83,761,5470,1402,284,28,196,593.0,1348.0,81.0,44.0,705,646,4.01,3,12,43,1393,183,493,1351,94,164,0.984,98,98,0,0,0,0,56,0.256307,25.8,0.330,0.326,86.0
1,2015,MIL,68,655,5480,1378,274,34,145,412.0,1299.0,84.0,34.0,737,682,4.28,1,7,40,1432,176,517,1260,116,164,0.981,101,101,0,0,0,0,-82,0.251460,27.0,0.290,0.289,78.5
2,2017,ARI,93,812,5525,1405,314,39,220,578.0,1456.0,103.0,27.0,659,586,3.66,2,11,43,1309,171,516,1482,108,140,0.982,110,110,0,1,0,0,153,0.254299,25.5,0.323,0.319,77.5
3,2019,ANA,72,769,5542,1368,268,21,220,586.0,1276.0,65.0,42.0,868,820,5.12,0,2,32,1417,267,576,1404,92,118,0.984,98,98,0,0,0,0,-99,0.246842,25.2,0.327,0.321,83.5
4,2017,ANA,80,710,5415,1314,251,14,186,523.0,1198.0,136.0,46.0,709,672,4.20,1,10,43,1373,224,470,1312,80,135,0.986,96,96,0,0,0,0,1,0.242659,23.4,0.318,0.312,79.5
5,2019,ARI,85,813,5633,1419,288,40,220,540.0,1360.0,88.0,40.0,743,691,4.25,0,11,45,1400,220,516,1427,86,136,0.986,101,101,0,0,0,0,70,0.251908,24.4,0.319,0.317,77.0
6,2018,BAL,47,622,5507,1317,242,15,188,422.0,1412.0,81.0,35.0,892,824,5.18,2,7,28,1552,234,589,1203,104,159,0.982,96,97,0,0,0,0,-270,0.239150,24.0,0.294,0.297,77.5
7,2017,LAD,104,770,5408,1347,312,20,221,649.0,1380.0,77.0,38.0,580,543,3.38,2,16,51,1226,184,442,1549,88,131,0.985,97,96,1,0,1,0,190,0.249075,25.0,0.334,0.330,93.5
8,2016,SDP,68,686,5419,1275,257,26,177,449.0,1500.0,125.0,36.0,770,708,4.43,1,9,35,1425,183,569,1222,109,165,0.982,99,99,0,0,0,0,-84,0.235283,25.6,0.295,0.291,75.0
9,2018,TOR,73,709,5477,1336,320,16,217,499.0,1387.0,47.0,37.0,832,772,4.85,0,3,39,1476,208,551,1298,101,138,0.983,97,98,0,0,0,0,-123,0.243929,25.0,0.316,0.325,81.5

In [21]:
df.describe()

,yearID,W,R,AB,H,2B,3B,HR,BB,SO,SB,SF,RA,ER,ERA,CG,SHO,SV,HA,HRA,BBA,SOA,E,DP,FP,BPF,PPF,DivWin_Y,WCWin_Y,LgWin_Y,WSWin_Y,run_diff,ba,linedrivepercent,xobp,xwoba,vegas_win_total
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.00000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.00000,150.000000
mean,2017.000000,80.973333,733.800000,5524.660000,1397.693333,277.920000,28.260000,193.233333,510.473333,1337.080000,82.153333,39.993333,733.800000,678.793333,4.227667,2.220000,9.706667,41.140000,1397.693333,193.233333,510.473333,1337.080000,94.480000,141.466667,0.984160,100.100000,100.033333,0.20000,0.133333,0.066667,0.033333,0.000000,0.252916,25.481333,0.312853,0.31086,81.230000
std,1.418951,12.675054,76.678532,71.727376,67.263475,25.641964,9.395437,38.930573,67.462910,126.072075,27.325219,7.515083,88.432585,82.542509,0.532812,2.163982,3.796054,7.530725,90.749448,31.210353,59.398969,134.212919,14.837247,18.922188,0.002425,5.663672,5.514370,0.40134,0.341073,0.250279,0.180107,125.170488,0.009899,1.265727,0.011798,0.01301,8.031948
min,2015.000000,47.000000,573.000000,5330.000000,1251.000000,222.000000,5.000000,100.000000,375.000000,973.000000,19.000000,26.000000,525.000000,478.000000,2.940000,0.000000,2.000000,25.000000,1125.000000,110.000000,364.000000,1046.000000,63.000000,95.000000,0.978000,89.000000,89.000000,0.00000,0.000000,0.000000,0.000000,-333.000000,0.233570,22.400000,0.284000,0.28300,59.000000
25%,2016.000000,71.000000,680.500000,5478.250000,1349.250000,259.250000,21.000000,165.250000,460.250000,1253.500000,63.000000,35.000000,670.500000,614.000000,3.802500,1.000000,7.000000,36.000000,1340.250000,174.000000,474.000000,1233.250000,85.000000,129.250000,0.983000,96.250000,97.000000,0.00000,0.000000,0.000000,0.000000,-97.500000,0.245868,24.700000,0.306000,0.30200,75.750000
50%,2017.000000,81.000000,729.000000,5520.500000,1392.000000,277.000000,28.000000,193.500000,512.000000,1331.500000,78.000000,39.500000,723.000000,669.500000,4.180000,2.000000,9.000000,41.000000,1399.500000,189.500000,506.000000,1332.500000,94.000000,141.000000,0.984000,99.000000,99.000000,0.00000,0.000000,0.000000,0.000000,-4.500000,0.252226,25.300000,0.313000,0.31000,81.500000
75%,2018.000000,91.000000,773.250000,5566.500000,1441.500000,292.000000,33.750000,220.000000,561.750000,1424.750000,98.000000,44.000000,795.500000,735.750000,4.607500,3.000000,12.000000,46.000000,1455.250000,213.750000,548.750000,1420.000000,102.750000,154.750000,0.986000,103.000000,103.000000,0.00000,0.000000,0.000000,0.000000,88.500000,0.258923,26.175000,0.320750,0.31975,86.000000
max,2019.000000,108.000000,943.000000,5770.000000,1598.000000,355.000000,56.000000,307.000000,656.000000,1595.000000,181.000000,63.000000,981.000000,897.000000,5.590000,11.000000,21.000000,62.000000,1617.000000,305.000000,653.000000,1687.000000,136.000000,190.000000,0.989000,119.000000,118.000000,1.00000,1.000000,1.000000,1.000000,280.000000,0.281834,29.300000,0.337000,0.34500,97.500000

In [22]:
mets = df.loc[df['franchID']=='NYM']
mets.head()

,yearID,franchID,W,R,AB,H,2B,3B,HR,BB,SO,SB,SF,RA,ER,ERA,CG,SHO,SV,HA,HRA,BBA,SOA,E,DP,FP,BPF,PPF,DivWin_Y,WCWin_Y,LgWin_Y,WSWin_Y,run_diff,ba,linedrivepercent,xobp,xwoba,vegas_win_total
11,2018,NYM,77,676,5468,1282,265,34,170,566.0,1404.0,71.0,42.0,707,661,4.07,3,15,41,1364,185,484,1446,88,121,0.985,90,91,0,0,0,0,-31,0.234455,23.4,0.307,0.297,80.5
26,2017,NYM,70,735,5510,1379,286,28,224,529.0,1291.0,58.0,37.0,863,799,5.01,2,5,34,1538,220,593,1374,92,125,0.984,97,97,0,0,0,0,-128,0.250272,24.5,0.316,0.315,88.5
72,2016,NYM,87,671,5459,1342,240,19,218,517.0,1302.0,42.0,41.0,617,574,3.57,1,13,55,1397,152,439,1396,90,138,0.985,102,102,0,1,0,0,54,0.245833,26.5,0.314,0.310,89.0
118,2015,NYM,90,683,5527,1351,295,17,177,488.0,1290.0,51.0,32.0,613,557,3.43,1,14,50,1341,152,383,1337,88,131,0.986,94,92,1,0,1,0,70,0.244436,26.8,0.310,0.309,81.5
134,2019,NYM,86,791,5624,1445,280,17,242,516.0,1384.0,56.0,27.0,737,688,4.24,3,12,38,1405,204,500,1520,99,129,0.983,92,92,0,0,0,0,54,0.256935,25.4,0.322,0.319,83.5

In [25]:
df_yearly = pd.read_pickle('data/new_df.pkl')
df_yearly.tail(10)

,date,team,team_score,opponent_score,Hits,RBI,doubles,strikeouts,def_assists,def_errors,def_doubleplays,pitchers_used,Rolling3_runs_scored,Rolling3_runs_against,Rolling3_run_diff,Rolling3_hits,Rolling3_RBI,Rolling3_doubles,Rolling3_strikeouts,Rolling3_def_assists,Rolling3_def_errors,Rolling3_doubleplays,Rolling3_pitchers_used,game_result
14564,2019-09-29,COL,4,3,8,3,0,15,9,1,0,8,17.0,17.0,0.0,29.0,16.0,5.0,32.0,33.0,1.0,5.0,16.0,1
14574,2019-09-29,MIN,4,5,6,4,1,8,8,0,0,6,20.0,9.0,11.0,33.0,18.0,6.0,17.0,12.0,0.0,1.0,14.0,0
14576,2019-09-29,ANA,5,8,8,5,4,15,10,0,0,7,7.0,13.0,-6.0,15.0,6.0,3.0,27.0,29.0,0.0,4.0,22.0,0
14562,2019-09-29,SEA,3,1,7,3,2,7,8,0,0,7,5.0,7.0,-2.0,18.0,5.0,4.0,25.0,27.0,2.0,4.0,16.0,1
14573,2019-09-29,DET,3,5,7,3,1,8,7,1,1,4,9.0,20.0,-11.0,26.0,9.0,4.0,31.0,17.0,3.0,3.0,13.0,0
14573,2019-09-29,CHW,5,3,4,4,2,12,15,0,2,6,18.0,5.0,13.0,29.0,17.0,4.0,24.0,30.0,2.0,1.0,12.0,1
14566,2019-09-29,PHI,3,4,13,3,1,10,7,1,1,7,17.0,13.0,4.0,28.0,16.0,6.0,32.0,38.0,0.0,2.0,14.0,0
14563,2019-09-29,ARI,1,0,7,1,2,8,14,0,2,5,21.0,15.0,6.0,19.0,18.0,7.0,24.0,27.0,3.0,2.0,14.0,1
14569,2019-09-29,STL,9,0,9,8,0,7,11,0,2,3,15.0,25.0,-10.0,24.0,13.0,2.0,36.0,25.0,2.0,0.0,20.0,1
14568,2019-09-29,LAD,9,0,12,9,1,8,10,0,2,8,12.0,2.0,10.0,21.0,12.0,5.0,30.0,16.0,2.0,0.0,15.0,1

In [28]:
wins = df_yearly.loc[df_yearly['game_result']==1]
wins.describe()

,team_score,opponent_score,Hits,RBI,doubles,strikeouts,def_assists,def_errors,def_doubleplays,pitchers_used,Rolling3_runs_scored,Rolling3_runs_against,Rolling3_run_diff,Rolling3_hits,Rolling3_RBI,Rolling3_doubles,Rolling3_strikeouts,Rolling3_def_assists,Rolling3_def_errors,Rolling3_doubleplays,Rolling3_pitchers_used,game_result
count,14576.000000,14576.000000,14576.000000,14576.000000,1.457600e+04,14576.000000,14576.000000,14576.000000,14576.000000,14576.000000,14576.000000,14576.000000,14576.000000,14576.000000,14576.000000,1.457600e+04,14576.000000,14576.000000,14576.000000,14576.000000,14576.000000,14576.0
mean,6.199780,2.707259,10.106888,5.913625,6.973286e+05,7.641465,9.661979,0.468716,0.923299,4.140368,13.504871,13.169525,0.335346,26.314215,12.890505,2.096877e+06,24.308932,28.744649,1.747462,2.701153,12.614572,1.0
std,3.089897,2.048065,5.185065,3.021549,8.300032e+07,2.888652,3.173924,0.705175,1.313298,1.428713,5.717642,5.644968,7.835911,10.709361,5.543239,1.437509e+08,5.724935,5.782683,1.392196,2.272216,2.478015,0.0
min,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-34.000000,8.000000,0.000000,0.000000e+00,7.000000,10.000000,0.000000,0.000000,3.000000,1.0
25%,4.000000,1.000000,8.000000,4.000000,1.000000e+00,6.000000,7.000000,0.000000,0.000000,3.000000,9.000000,9.000000,-5.000000,22.000000,9.000000,3.000000e+00,20.000000,25.000000,1.000000,1.000000,11.000000,1.0
50%,6.000000,2.000000,10.000000,5.000000,2.000000e+00,7.000000,10.000000,0.000000,1.000000,4.000000,13.000000,13.000000,0.000000,26.000000,12.000000,5.000000e+00,24.000000,29.000000,2.000000,2.000000,12.000000,1.0
75%,8.000000,4.000000,12.000000,8.000000,3.000000e+00,9.000000,12.000000,1.000000,1.000000,5.000000,17.000000,17.000000,5.000000,30.000000,16.000000,7.000000e+00,28.000000,32.250000,3.000000,4.000000,14.000000,1.0
max,25.000000,14.000000,259.000000,25.000000,1.002000e+10,26.000000,28.000000,5.000000,39.000000,13.000000,47.000000,42.000000,32.000000,289.000000,46.000000,1.002000e+10,52.000000,51.000000,9.000000,40.000000,25.000000,1.0

In [29]:
losses = df_yearly.loc[df_yearly['game_result']==0]
losses.describe()

,team_score,opponent_score,Hits,RBI,doubles,strikeouts,def_assists,def_errors,def_doubleplays,pitchers_used,Rolling3_runs_scored,Rolling3_runs_against,Rolling3_run_diff,Rolling3_hits,Rolling3_RBI,Rolling3_doubles,Rolling3_strikeouts,Rolling3_def_assists,Rolling3_def_errors,Rolling3_doubleplays,Rolling3_pitchers_used,game_result
count,14578.000000,14578.000000,14578.000000,14578.000000,1.457800e+04,14578.000000,14578.000000,14578.000000,14578.000000,14578.000000,14578.000000,14578.000000,14578.000000,14578.000000,14578.000000,1.457800e+04,14578.000000,14578.000000,14578.000000,14578.000000,14578.000000,14578.0
mean,2.707024,6.199067,7.326931,2.589793,1.589752e+04,8.666278,9.450473,0.700988,0.884483,4.259569,13.222458,13.554877,-0.332419,26.003018,12.624708,4.280236e+04,24.597064,28.612018,1.774523,2.724173,12.582110,0.0
std,2.048022,3.090285,5.793879,2.005121,1.185888e+06,3.046454,3.097983,0.861453,1.264430,1.384104,5.659058,5.771831,7.939501,9.152148,5.487810,2.029324e+06,5.721349,5.725978,1.399092,2.222727,2.454864,0.0
min,0.000000,1.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-36.000000,6.000000,0.000000,0.000000e+00,5.000000,10.000000,0.000000,0.000000,4.000000,0.0
25%,1.000000,4.000000,5.000000,1.000000,0.000000e+00,7.000000,7.000000,0.000000,0.000000,3.000000,9.000000,9.000000,-5.000000,21.000000,9.000000,3.000000e+00,21.000000,25.000000,1.000000,1.000000,11.000000,0.0
50%,2.000000,6.000000,7.000000,2.000000,1.000000e+00,8.000000,9.000000,0.000000,1.000000,4.000000,13.000000,13.000000,0.000000,25.000000,12.000000,5.000000e+00,24.000000,28.000000,2.000000,2.000000,12.000000,0.0
75%,4.000000,8.000000,9.000000,4.000000,2.000000e+00,11.000000,11.000000,1.000000,1.000000,5.000000,17.000000,17.000000,5.000000,30.000000,16.000000,7.000000e+00,28.000000,32.000000,3.000000,4.000000,14.000000,0.0
max,14.000000,25.000000,273.000000,13.000000,1.000010e+08,26.000000,26.000000,6.000000,36.000000,13.000000,46.000000,47.000000,36.000000,296.000000,44.000000,1.200221e+08,50.000000,52.000000,9.000000,42.000000,27.000000,0.0

# SQL

set batch_id = '22092029' ;
set bench_table = concat('table_name_', $batch_id) ;

proj_factors2 as (
select
    p.proj_factor,
    p.eligibility,
    d.*
from proj_factor1 as p
    left join demos as d
    on p.userID = d.userID )